notifications:
  email: false
language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install coveralls
  - pip install -r requirements.txt
script:
  - cd .. && coverage run --source=blockchain-python --omit="blockchain-python/test_*" -m unittest blockchain-python.test_unit blockchain-python.test_integration
after_success:
  coveralls
