notifications:
  email: false
language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install coveralls
  - pip install -r requirements.txt
script:
  - coverage run --source=blockchain --omit="blockchain/test_*" -m unittest blockchain.test_unit blockchain.test_integration
after_success:
  coveralls
