notifications:
  email: false
language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install coveralls
  - pip install -r requirements.txt
script:
  - cd .. && coverage run --source=freechain-python --omit="freechain-python/test_*" -m unittest freechain-python.test_unit freechain-python.test_integration
after_success:
  coveralls
